### ISSUE TITLE
official

### ISSUE THREAD

**Issue by Zitrax** [kunaltyagi/nsiqcppstyle#2]
Just a question, is this the new "official" home for nsiqcppstyle or is it just your personal copy ?

**Comment by kunaltyagi** [comment]
"Official: nsiqcppstyle has not been maintained for a long time. 
I am maintinaing it for now, but it is still me personal copy. I have entertained a few feature requests every now and then, so this can be treated like an active fork, I guess.

**Comment by Zitrax** [comment]
Ok, thank you. I was simply curious since the original source had shut down. I haven't tried it out yet but I probably will.
