### ISSUE TITLE
Line continuations on nsiqcppstyle_exe.py

### ISSUE THREAD

**Issue by alexgh79** [kunaltyagi/nsiqcppstyle#20]
nsiqcppstyle_exe.py lines: 293 - 294 should have \ to continue the line. This can lead to compilation errors:

> File "/usr/lib/nsiqcppstyle/nsiqcppstyle_exe.py", line 293
>     if fileExtension in cExtendstionSet and
>                                           ^
> SyntaxError: invalid syntax

Existing Code:
>                      if fileExtension in cExtendstionSet and
>                                 basefilelist.IsNewOrChanged(eachFile) and

Suggested Replacement:
                        if fileExtension in cExtendstionSet and \
                                basefilelist.IsNewOrChanged(eachFile) and \

**Comment by kunaltyagi** [comment]
Could you please create a PR with the proposed change and a test case?
