### ISSUE TITLE
RULE_4_5_A_matching_braces_inside_of_function_should_be_located_same_column reported as violated on lambdas

### ISSUE THREAD

**Issue by seltzy** [kunaltyagi/nsiqcppstyle#3]
Lambdas seem to always produce violations of RULE_4_5_A_matching_braces_inside_of_function_should_be_located_same_column

For example, using async boost callbacks:
```
auto onAccept = [this](boost::system::error_code ec) {
    if (!ec) {
      RxSessionType::create(this)->start();
    } else {
      std::cout << "Experienced error on accept: " << ec << std::endl;
    }
    _acceptConnections();
};
```
In the above, it would report both the lambda body braces and if/else braces.

**Comment by kunaltyagi** [comment]
This tool has never quite kept progress with the march of C++. 
Despite that, the rule doesn't actually produce an erroneous output. If you note, the *lambda* opens in a different column compare to its closing column. Same with your ```if-else``` braces.

Your brace style and the rule applied are incompatible. Might I suggest using 
**RULE_4_5_A_braces_inside_of_function_should_be_located_in_end_of_line** and
**RULE_4_5_B_use_braces_even_for_one_statement** instead? Or maybe you can develop your own rule.

Else, if you want to not change the rules, change the coding to slightly longer (or something similar)
```c++
auto onAccept = [this](boost::system::error_code ec) 
    {
        if (!ec) 
        {
            RxSessionType::create(this)->start();
        } 
        else 
        {
            std::cout << "Experienced error on accept: " << ec << std::endl;
        }
    _acceptConnections();
};
```
