### ISSUE TITLE
règle RULE_3_2_F_use_representitive_classname_for_cpp_filename ne gère pas les classes finales

### ISSUE THREAD

**Issue by leonarf** [kunaltyagi/nsiqcppstyle#6]
La règle RULE_3_2_F_use_representitive_classname_for_cpp_filename qui vérifie le nom des fichiers en fonction de la classe qu'il contient. Le problème est que lorsqu'on déclare une classe finale (class toto final), le parser semble interpréter final comme une classe :-(

Je propose le test unitaire suivant :

    def test9(self):
        self.Analyze("test/CamRecorderFactory.h",
"""
class CamRecorderFactory final
{
};
""")
        assert not  CheckErrorContent(__name__)

**Comment by leonarf** [comment]
Pour corriger, je propose d'ajouter le mot clef reservé 
    "final":"IGNORE"
dans le fichier nsiqcppstyle_checker.py

**Comment by leonarf** [comment]
Fixed by my Pull Request :-)

**Comment by kunaltyagi** [comment]
Hi, I checked your PR #7, and it does fix the issue. However, could you edit your first comment on this thread to be in English? The second comment is guessable, but the first one requires judicious use of a translation service. This might help people who search for this issue in the future.
